### PR TITLE
Fix build on Jetson Xavier AGX

### PR DESCRIPTION
**Pull request by elaye**
Hello,
I was trying to build `tch` on the Jetson Xavier AGX board (arm64) and I got two errors.
This PR fixes the issue in case you're interested.

### CODE REVIEW

**Comment by LaurentMazare** [comment]
Thanks for the PR, the bool_to_option feature in `build.rs` seems to break the CI.
Are you running with the stable channel?

**Comment by elaye** [comment]
Ah, yes sorry I was building on nightly.
I removed the feature flag so the CI should pass on stable now.

**Comment by elaye** [comment]
So it seems that `char` is interpreted differently on ARM. I added a cast to `libc::c_char` that should do the trick.

However I can't compile on my machine without adding `#![feature(bool_to_option)]` to `torch_sys::build.rs` and I don't understand why, if it passes the CI without it.

**Comment by LaurentMazare** [comment]
The bool_to_option feature indeed seems mostly unrelated so not sure what is going on, the CI also runs on nightly and doesn't seem to hit the issue. Anyway I'll merge the PR, thanks!

**Review by LaurentMazare — APPROVED** [review]

**Pull request merged**
