### PR TITLE
Add the autocast function to run a closure in mixed-precision

### PR DESCRIPTION
**Pull request by danieldk**
I have made this a draft PR, because I can't currently test this (all our GPUs that support mixed-precision have jobs running for multiple days). Also, I haven't added any unit tests, since actually testing this would require a CUDA-capable GPU.

### CODE REVIEW

**Comment by LaurentMazare** [comment]
Looks very nice thanks for the PR. Not having unit tests run automatically sounds reasonable but maybe we could have some tests or an example behind some feature gate ?
Also note that the appveyor CI fails because of missing autocast symbols on the windows build. I haven't investigated but maybe these symbols are not available on windows somehow?

**Comment by danieldk** [comment]
> Looks very nice thanks for the PR. Not having unit tests run automatically sounds reasonable but maybe we could have some tests or an example behind some feature gate ?

I'll try to add some tests behind a feature gate.

> Also note that the appveyor CI fails because of missing autocast symbols on the windows build. I haven't investigated but maybe these symbols are not available on windows somehow?

I think this was caused by name mangling. The new symbols were not in `torch_api.h`, so not within `extern "C"`. Fixed now.

**Comment by danieldk** [comment]
I have added an `autocast-tests` feature, which runs a simple test case (with nesting of `autocast`). I passes with flying colors on a Tesla P100.

**Comment by LaurentMazare** [comment]
Merged, thanks for the PR!

**Pull request merged**
